# Generated by Django 5.2.3 on 2025-06-15 17:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_transactionhistory_delete_transaction_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionhistory",
            name="transfer_method",
        ),
        migrations.AddField(
            model_name="account",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="category",
            field=models.CharField(
                choices=[
                    ("food", "식비"),
                    ("transport", "교통"),
                    ("entertainment", "여가"),
                    ("shopping", "쇼핑"),
                    ("saving", "저축"),
                    ("etc", "기타"),
                ],
                default="etc",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
