# Generated by Django 5.2.3 on 2025-06-12 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about",
                    models.CharField(
                        choices=[("income", "총 수입"), ("expense", "총 지출")],
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("weekly", "매주"), ("monthly", "매월")], max_length=20
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("description", models.TextField()),
                ("result_image", models.ImageField(upload_to="analysis_results/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
