# Generated by Django 5.2.3 on 2025-06-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="type",
            field=models.CharField(
                choices=[("weekly", "매주"), ("monthly-category", "월간 카테고리별")],
                max_length=20,
            ),
        ),
    ]
