# Generated by Django 5.2.3 on 2025-06-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_alter_analysis_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
